### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by fcakyon** [conda-forge/pycocotools-feedstock#16]
Why dont this conda package support windows? Original pycocotools pypi package supports windows without any issues.

**Comment by ashnair1** [comment]
@erykoff @hadim Any chance of adding windows support?

**Comment by ashnair1** [comment]
Seems skipping windows was intentional according to [this](https://github.com/conda-forge/pycocotools-feedstock/blob/10400d6dbab5729f690a9d17c371319cb8c25200/recipe/meta.yaml#L15) line in `meta.yaml`. Any reason why?

**Comment by ashnair1** [comment]
Pinging @erykoff @hadim

**Comment by mukhery** [comment]
closing as windows support was added in #20
